replicaCount: 1

image:
  repository: 517169952856.dkr.ecr.us-east-1.amazonaws.com/tc2-flask-eks-app
  tag: 5e8994a7c5f4687facf69a13f3cbabd44aefca07
  pullPolicy: Always

service:
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

ingress:
  enabled: true
  className: alb